version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    requires:
      - build
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - run: |
          ls

workflows:
  digitalocean-deploy:
    jobs:
      - build
      - deploy
