version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    executor: node/default
    parameters:
      token:
        type: string
        default: $DOPPLER_TOKEN_PRD
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: >-
            (curl
            -Ls
            --tlsv1.2
            --proto "=https"
            --retry 3
            https://cli.doppler.com/install.sh
            || wget
            -t 3
            -qO- https://cli.doppler.com/install.sh)
            | sudo sh
          name: Install Doppler
      - run:
          command: >-
            doppler secrets download
            --format=env-no-quotes
            --no-file
            --token << parameters.token >>
            | grep VUE_APP
            > ~/project/.env.production
          name: Fetch env variables
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    parameters:
      app_dirname:
        type: string
        default: $CIRCLE_PROJECT_REPONAME
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: >-
            tar
            czvf $CIRCLE_PROJECT_REPONAME-$CIRCLE_SHA1.tar.gz
            -C ~/project/dist .
          name: Compress build
      - run:
          command: >-
            scp
            -oStrictHostKeyChecking=no
            -v
            $CIRCLE_PROJECT_REPONAME-$CIRCLE_SHA1.tar.gz
            $USER@$IP:~/.
          name: Copy build
      - run:
          command: >-
            ssh
            -oStrictHostKeyChecking=no
            -v
            $USER@$IP
            "./deploy-vue.sh
            << parameters.app_dirname >>
            $CIRCLE_PROJECT_REPONAME-$CIRCLE_SHA1.tar.gz"
          name: Run remote deployment script

workflows:
  digitalocean-deploy:
    jobs:
      - build:
          name: build-prd
          filters:
            branches:
              only: master
      - build:
          name: build-stg
          token: $DOPPLER_TOKEN_STG
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build-prd
      - deploy:
          requires:
            - build-stg
          app_dirname: $CIRCLE_PROJECT_REPONAME-stg
